'use client'

import { useState, useRef, useEffect } from 'react'
import { useTheme } from '@/lib/theme-context'
import { saveToHistory } from '@/lib/history' // Tutarlı geçmiş kaydı için
import { 
  Terminal, FileText, Send, Bot, 
  User, Command, CheckCircle2, AlertTriangle, Layers, ServerCrash, ShieldAlert
} from 'lucide-react'

const ATLAS_COMMANDS = [
  { id: '1', cmd: 'brainstorm {topic}', desc: 'Yapılandırılmış beyin fırtınası oturumu.' },
  { id: '2', cmd: 'create-competitor-analysis', desc: 'Rekabet analizi belgesi.' },
  { id: '3', cmd: 'create-project-brief', desc: 'Proje özeti oluşturma (BMAD).' },
  { id: '4', cmd: 'doc-out', desc: 'İlerleyen belgeyi .md olarak dışa aktarır.' },
  { id: '5', cmd: 'elicit', desc: 'Gereksinim çıkarma ve uç durum (kör nokta) bulma.' },
  { id: '6', cmd: 'perform-market-research', desc: 'Pazar araştırması.' },
  { id: '7', cmd: 'research-prompt {topic}', desc: 'Derin araştırma komutu.' },
  { id: '8', cmd: 'yolo', desc: 'Yolo Modu (Soru sormadan tüm taslağı bitirir).' },
  { id: '9', cmd: 'exit', desc: 'Personadan çıkar.' }
]

export default function AtlasStudioPage() {
  const { colors, accent, isDark } = useTheme()
  
  const [activeTab, setActiveTab] = useState<'brief'>('brief')
  const [inputValue, setInputValue] = useState('')
  const [showCommands, setShowCommands] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const [projectBrief, setProjectBrief] = useState({
    title: "YENİ PROJE TASLAĞI",
    problem: "Atlas'a fikrinizi söyleyin, BMAD standartlarında sizin yerinize doldursun.",
    solution: "Tüm teknik ve iş çözümü otomatik kurgulanacak.",
    inScope: [{ feature: "Siz sadece konuyu verin, Atlas dolduracak.", effort: "M" }],
    outOfScope: ["Kapsam dışı öğeler otomatik hesaplanacak."],
    risks: [{ description: "Elicit komutuyla zayıf noktalarınız bulunacak.", severity: "Low" }],
    techStack: ["Atlas mimariyi belirleyecek..."]
  })

  const [messages, setMessages] = useState<{role: string, content: string | React.ReactNode, time?: string}[]>([])

  useEffect(() => {
    setMessages([{
      role: 'agent',
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      content: (
        <div>
          <p>Merhaba! Ben Atlas, sizin BMAD İş Analistiniz. Kanıtlanmış BMAD-METHOD™ metodolojilerinde eğitim almış bir uzman olarak amacım, kapsamlı, profesyonel ve denetime hazır proje dokümantasyonu oluşturmak için sizi yapılandırılmış bir keşif sürecinden geçirmektir.</p>
          <p className="mt-3">Hazır olduğunuzda oturumumuzu yönlendirmek için aşağıdaki 9 komuttan herhangi birini kullanabilirsiniz:</p>
          <ul className="mt-2 space-y-1 pl-4 opacity-90 text-[12px] font-mono list-decimal">
            {ATLAS_COMMANDS.map(c => <li key={c.id}><strong>{c.cmd.replace(' {topic}', '')}</strong> : {c.desc}</li>)}
          </ul>
          <p className="mt-3">Başlamak için lütfen bir komut girin veya bir numara yazın.</p>
        </div>
      )
    }])
  }, [])

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [messages])

  // ==========================================
  // MARKDOWN (.MD) EXPORT FONKSİYONU
  // ==========================================
  const exportToMarkdown = () => {
    const mdContent = `# ${projectBrief.title.toUpperCase()}

## 1. PROBLEM VE BMAD ÇÖZÜMÜ
**Sorun Tespiti:** ${projectBrief.problem}
**Mimari Çözüm:** ${projectBrief.solution}

## 2. KAPSAM VE EFOR (IN-SCOPE / OUT-OF-SCOPE)
### IN-SCOPE (Eforlu)
${projectBrief.inScope.map((i: any) => `- [${i.effort || 'M'}] ${i.feature}`).join('\n')}

### OUT-OF-SCOPE
${projectBrief.outOfScope.map((i: string) => `- ${i}`).join('\n')}

## 3. TECH STACK VE RİSKLER
### ÖNERİLEN TECH STACK
${projectBrief.techStack.join(', ')}

### UÇ DURUMLAR (EDGE CASES)
${projectBrief.risks.map((r: any) => `- [${(r.severity || 'LOW').toUpperCase()}] ${r.description}`).join('\n')}

---
*Generated by BAI Platform - Atlas Studio (BMAD-METHOD)*
`;
    
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${projectBrief.title.replace(/\s+/g, '-').toLowerCase()}-bmad-brief.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value
    setInputValue(val)
    if (val.endsWith('/')) setShowCommands(true)
    else if (val.trim() === '') setShowCommands(false)
  }

  const handleCommandSelect = (cmd: string) => {
    setInputValue(`/${cmd.replace(' {topic}', '')} `)
    setShowCommands(false)
    inputRef.current?.focus()
  }

  const handleSendMessage = async () => {
    if (!inputValue.trim() || isLoading) return
    const inputClean = inputValue.trim().toLowerCase()
    const timeStr = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    const userMsg = { role: 'user', content: inputValue, time: timeStr }
    
    setMessages(prev => [...prev, userMsg])
    setInputValue('')
    setShowCommands(false)

    // EĞER KULLANICI 4, /doc-out VEYA doc-out YAZDIYSA
    if (inputClean === '4' || inputClean === '/doc-out' || inputClean === 'doc-out') {
      exportToMarkdown()
      setMessages(prev => [...prev, { 
        role: 'agent', 
        content: "Proje dokümanınız (Markdown formatında) bilgisayarınıza indiriliyor. İşlem tamamlandı! Başka bir komut (Örn: 9 exit) girmek ister misiniz?",
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }])
      
      // Geçmişe Kaydetme İşlemi
      await saveToHistory(
        'Atlas Studio',
        'doc-out (Doküman Çıktısı Alındı)',
        JSON.stringify(projectBrief, null, 2)
      )

      return; 
    }

    setIsLoading(true)

    try {
      const apiMessages = [...messages, userMsg].map(m => ({
        role: m.role === 'agent' ? 'assistant' : 'user',
        content: typeof m.content === 'string' ? m.content : "System Intro Prompt"
      }))

      const res = await fetch('/api/bmad', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: apiMessages })
      })

      if (!res.ok) throw new Error("Sunucu yanıt vermedi")
      
      const data = await res.json()

      setMessages(prev => [...prev, { 
        role: 'agent', 
        content: data.reply,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }])

      if (data.docUpdate) {
        setProjectBrief({
          title: data.docUpdate.title || projectBrief.title,
          problem: data.docUpdate.problem || projectBrief.problem,
          solution: data.docUpdate.solution || projectBrief.solution,
          inScope: data.docUpdate.inScope?.length ? data.docUpdate.inScope : projectBrief.inScope,
          outOfScope: data.docUpdate.outOfScope?.length ? data.docUpdate.outOfScope : projectBrief.outOfScope,
          risks: data.docUpdate.risks?.length ? data.docUpdate.risks : projectBrief.risks,
          techStack: data.docUpdate.techStack?.length ? data.docUpdate.techStack : projectBrief.techStack
        })
      }

      // History Tablosuna Kayıt
      const formattedOutput = `**Atlas Yanıtı:**\n${data.reply}\n\n**Güncellenen Mimari Kapsam:**\n${JSON.stringify(data.docUpdate, null, 2)}`
      await saveToHistory('Atlas Studio', userMsg.content, formattedOutput)

    } catch (error) {
      setMessages(prev => [...prev, { 
        role: 'agent', 
        content: "Analiz sırasında bir hata oluştu. Lütfen bağlantınızı kontrol edip tekrar deneyin.",
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }])
    } finally {
      setIsLoading(false)
    }
  }

  const getSeverityColor = (severity: string) => {
    switch (severity?.toLowerCase()) {
      case 'high': return { bg: '#ef444422', text: '#ef4444' }
      case 'medium': return { bg: '#f59e0b22', text: '#f59e0b' }
      case 'low': return { bg: '#10b98122', text: '#10b981' }
      default: return { bg: 'rgba(255,255,255,0.1)', text: '#94a3b8' }
    }
  }

  const getEffortColor = (effort: string) => {
    switch (effort?.toUpperCase()) {
      case 'S': return '#10b981'
      case 'M': return '#3b82f6'
      case 'L': return '#f59e0b'
      case 'XL': return '#ef4444'
      default: return accent
    }
  }

  const terminalBg = isDark ? '#09090b' : '#1e293b'
  const terminalHeader = isDark ? '#18181b' : '#0f172a'
  const terminalBorder = isDark ? '#27272a' : '#334155'

  return (
    <div style={{ display: 'flex', gap: '20px', height: 'calc(100vh - 120px)' }}>
      
      {/* SOL PANEL: ATLAS TERMİNALİ */}
      <div style={{ width: '40%', display: 'flex', flexDirection: 'column', background: terminalBg, borderRadius: '16px', border: `1px solid ${terminalBorder}`, overflow: 'hidden' }}>
        <div style={{ background: terminalHeader, padding: '12px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: `1px solid ${terminalBorder}` }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Terminal size={16} color={accent} />
            <span style={{ fontSize: '13px', fontWeight: '700', color: '#f8fafc' }}>ATLAS <span style={{opacity:0.5}}>(BMAD Architect)</span></span>
          </div>
          <div style={{ display: 'flex', gap: '6px' }}>
            <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444' }}></div>
            <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#f59e0b' }}></div>
            <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#10b981' }}></div>
          </div>
        </div>

        <div style={{ flex: 1, padding: '16px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {messages.map((msg, i) => (
            <div key={i} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', flexDirection: msg.role === 'user' ? 'row-reverse' : 'row' }}>
              <div style={{ width: '28px', height: '28px', borderRadius: '8px', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: msg.role === 'user' ? accent : 'rgba(255,255,255,0.1)', color: '#fff' }}>
                {msg.role === 'user' ? <User size={14} /> : <Bot size={14} />}
              </div>
              <div style={{ maxWidth: '85%', background: msg.role === 'user' ? accent + '22' : 'transparent', padding: msg.role === 'user' ? '10px 14px' : '4px 0', borderRadius: '12px', color: '#e2e8f0', fontSize: '13px', lineHeight: '1.6' }}>
                {msg.time && <div style={{ fontSize: '10px', color: msg.role==='user'?accent:'#94a3b8', marginBottom: '4px', fontWeight: '700' }}>{msg.role==='user'?'SEN':'ATLAS'} • {msg.time}</div>}
                {msg.content}
              </div>
            </div>
          ))}
          {isLoading && (
            <div style={{ display: 'flex', gap: '12px', alignItems: 'center', color: '#94a3b8', fontSize: '12px', fontStyle: 'italic' }}>
              <Bot size={14} /> Atlas sizin yerinize projeyi tasarlıyor...
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        <div style={{ padding: '16px', borderTop: `1px solid ${terminalBorder}`, position: 'relative', background: terminalHeader }}>
          {showCommands && (
            <div style={{ position: 'absolute', bottom: '100%', left: '16px', right: '16px', marginBottom: '12px', background: '#18181b', border: `1px solid ${accent}44`, borderRadius: '12px', overflow: 'hidden', zIndex: 10 }}>
              <div style={{ padding: '10px 12px', background: 'rgba(255,255,255,0.03)', fontSize: '11px', fontWeight: '700', color: '#94a3b8', borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Command size={12} /> BMAD STANDART KOMUTLARI
              </div>
              <div style={{ maxHeight: '200px', overflowY: 'auto', padding: '6px' }}>
                {ATLAS_COMMANDS.map((cmd) => (
                  <div key={cmd.id} onClick={() => handleCommandSelect(cmd.cmd)} style={{ padding: '8px 10px', borderRadius: '6px', cursor: 'pointer', display: 'flex', gap: '10px' }} onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'} onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
                    <div style={{ fontSize: '12px', fontWeight: '800', color: accent, background: accent+'15', padding: '2px 6px', borderRadius: '4px', height: 'fit-content' }}>{cmd.id}</div>
                    <div>
                      <div style={{ fontSize: '13px', fontWeight: '700', color: '#f8fafc' }}>/{cmd.cmd.replace(' {topic}', '')}</div>
                      <div style={{ fontSize: '11px', color: '#94a3b8' }}>{cmd.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
          <div style={{ display: 'flex', alignItems: 'center', background: 'rgba(0,0,0,0.3)', border: `1px solid ${terminalBorder}`, borderRadius: '10px', padding: '4px' }}>
            <input 
              ref={inputRef}
              value={inputValue}
              onChange={handleInputChange}
              onKeyDown={e => e.key === 'Enter' && handleSendMessage()}
              disabled={isLoading}
              placeholder="Süreci başlatmak için (Örn: 8) yazın veya talebinizi anlatın..."
              style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: '#f8fafc', padding: '10px', fontSize: '13px' }}
            />
            <button onClick={handleSendMessage} disabled={isLoading || !inputValue.trim()} style={{ background: accent, color: '#fff', border: 'none', width: '36px', height: '36px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', opacity: isLoading ? 0.5 : 1 }}>
              <Send size={16} />
            </button>
          </div>
        </div>
      </div>

      {/* SAĞ PANEL: DİNAMİK MİMARİ DOKÜMANI */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', background: colors.card, borderRadius: '16px', border: `1px solid ${colors.border}`, overflow: 'hidden' }}>
        <div style={{ display: 'flex', borderBottom: `1px solid ${colors.border}`, background: isDark ? 'rgba(0,0,0,0.2)' : '#f8fafc', padding: '0 16px' }}>
          <button onClick={() => setActiveTab('brief')} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '16px 20px', background: activeTab === 'brief' ? colors.card : 'transparent', border: 'none', borderBottom: activeTab === 'brief' ? `2px solid ${accent}` : '2px solid transparent', color: activeTab === 'brief' ? accent : colors.textMuted, fontSize: '13px', fontWeight: '700', cursor: 'pointer' }}>
            <ShieldAlert size={16} /> BMAD-METHOD™ Kapsam Dokümanı
          </button>
        </div>

        <div style={{ flex: 1, padding: '32px', overflowY: 'auto' }}>
          {activeTab === 'brief' && (
            <div style={{ animation: 'fadeIn 0.3s', maxWidth: '850px', margin: '0 auto' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '32px' }}>
                <h1 style={{ fontSize: '28px', fontWeight: '800', color: colors.text, margin: 0, textTransform: 'uppercase' }}>{projectBrief.title}</h1>
              </div>

              {/* BÖLÜM 1: PROBLEM & ÇÖZÜM */}
              <div style={{ marginBottom: '32px' }}>
                <h3 style={{ fontSize: '16px', fontWeight: '800', color: accent, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <div style={{width:'24px', height:'24px', background:accent, color:'#fff', borderRadius:'6px', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'12px'}}>1</div> PROBLEM VE BMAD ÇÖZÜMÜ
                </h3>
                <div style={{ background: isDark ? 'rgba(255,255,255,0.03)' : '#f8fafc', padding: '20px', borderRadius: '12px', border: `1px solid ${colors.border}` }}>
                  <p style={{ fontSize: '14px', color: colors.text, lineHeight: '1.6', margin: '0 0 12px 0' }}><strong>Sorun Tespiti:</strong> {projectBrief.problem}</p>
                  <p style={{ fontSize: '14px', color: colors.text, lineHeight: '1.6', margin: 0 }}><strong>Mimari Çözüm:</strong> {projectBrief.solution}</p>
                </div>
              </div>

              {/* BÖLÜM 2: TECH STACK VE RİSKLER */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '32px' }}>
                <div style={{ border: `1px solid ${colors.border}`, background: isDark ? 'rgba(255,255,255,0.02)' : '#f8fafc', padding: '20px', borderRadius: '12px' }}>
                  <div style={{ fontSize: '13px', fontWeight: '800', color: colors.text, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '6px' }}><Layers size={16} color={accent} /> BMAD TECH STACK</div>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                    {projectBrief.techStack.map((tech, idx) => (
                      <span key={idx} style={{ background: isDark?'#27272a':'#e2e8f0', color: colors.text, padding: '4px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: '600', border: `1px solid ${colors.border}` }}>
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>

                <div style={{ border: `1px solid ${colors.border}`, background: isDark ? 'rgba(255,255,255,0.02)' : '#f8fafc', padding: '20px', borderRadius: '12px' }}>
                  <div style={{ fontSize: '13px', fontWeight: '800', color: colors.text, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '6px' }}><ServerCrash size={16} color="#ef4444" /> UÇ DURUMLAR (EDGE CASES)</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                    {projectBrief.risks.map((risk, idx) => {
                      const riskColors = getSeverityColor(risk.severity)
                      return (
                        <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
                          <span style={{ background: riskColors.bg, color: riskColors.text, padding: '2px 6px', borderRadius: '4px', fontSize: '10px', fontWeight: '800', marginTop: '2px' }}>{risk.severity?.toUpperCase() || 'LOW'}</span>
                          <span style={{ fontSize: '13px', color: '#94a3b8', lineHeight: '1.4' }}>{risk.description}</span>
                        </div>
                      )
                    })}
                  </div>
                </div>
              </div>

              {/* BÖLÜM 3: KAPSAM VE EFOR */}
              <div>
                <h3 style={{ fontSize: '16px', fontWeight: '800', color: accent, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <div style={{width:'24px', height:'24px', background:accent, color:'#fff', borderRadius:'6px', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'12px'}}>3</div> KAPSAM VE EFOR (IN-SCOPE / OUT-OF-SCOPE)
                </h3>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                  <div style={{ border: `1px solid #10b98144`, background: '#10b9810a', padding: '20px', borderRadius: '12px' }}>
                    <div style={{ fontSize: '13px', fontWeight: '800', color: '#10b981', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '6px' }}><CheckCircle2 size={16} /> IN-SCOPE (Eforlu)</div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                      {projectBrief.inScope.map((item: any, idx) => (
                        <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
                          <span style={{ background: getEffortColor(item.effort)+'22', color: getEffortColor(item.effort), border: `1px solid ${getEffortColor(item.effort)}55`, width: '22px', height: '22px', borderRadius: '4px', fontSize: '10px', fontWeight: '800', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                            {item.effort || 'M'}
                          </span>
                          <span style={{ fontSize: '13px', color: colors.text, lineHeight: '1.4' }}>{item.feature}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                  <div style={{ border: `1px solid #ef444444`, background: '#ef44440a', padding: '20px', borderRadius: '12px' }}>
                    <div style={{ fontSize: '13px', fontWeight: '800', color: '#ef4444', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '6px' }}><AlertTriangle size={16} /> OUT-OF-SCOPE</div>
                    <ul style={{ fontSize: '13px', color: colors.text, paddingLeft: '16px', lineHeight: '1.8', margin: 0 }}>
                      {projectBrief.outOfScope.map((item, idx) => <li key={idx}>{item}</li>)}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}